//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE0_CV_start
  (
   //////////// CLOCK //////////
   input         CLOCK_50,
   input         CLOCK2_50,
   input         CLOCK3_50,
   inout         CLOCK4_50,

   //////////// SDRAM //////////
   output [12:0] DRAM_ADDR,
   output [1:0]  DRAM_BA,
   output        DRAM_CAS_N,
   output        DRAM_CKE,
   output        DRAM_CLK,
   output        DRAM_CS_N,
   inout [15:0]  DRAM_DQ,
   output        DRAM_LDQM,
   output        DRAM_RAS_N,
   output        DRAM_UDQM,
   output        DRAM_WE_N,

   //////////// SEG7 //////////
   output [6:0]  HEX0,
   output [6:0]  HEX1,
   output [6:0]  HEX2,
   output [6:0]  HEX3,
   output [6:0]  HEX4,
   output [6:0]  HEX5,

   //////////// KEY //////////
   input [3:0]   KEY,
   input         RESET_N,

   //////////// LED //////////
   output [9:0]  LEDR,

   //////////// PS2 //////////
   inout         PS2_CLK,
   inout         PS2_CLK2,
   inout         PS2_DAT,
   inout         PS2_DAT2,

   //////////// SW //////////
   input [9:0]   SW,

   //////////// VGA //////////
   output [3:0]  VGA_B,
   output [3:0]  VGA_G,
   output        VGA_HS,
   output [3:0]  VGA_R,
   output        VGA_VS,

   //////////// SD //////////
   output        SD_CLK,
   inout         SD_CMD,
   inout [3:0]   SD_DATA,
   //////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
   inout [35:0]  GPIO_0,

   //////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
   inout [35:0]  GPIO_1
   );



  //=======================================================
  //  REG/WIRE declarations
  //=======================================================




  //=======================================================
  //  Structural coding
  //=======================================================

  // All inout port turn to tri-state
  assign CLOCK4_50 = 1'bz;
  assign DRAM_DQ = 16'hzzzz;
  assign PS2_CLK = 1'bz;
  assign PS2_CLK2 = 1'bz;
  assign PS2_DAT = 1'bz;
  assign PS2_DAT2 = 1'bz;
  assign SD_CMD = 1'bz;
  assign SD_DATA = 4'hz;
  assign GPIO_0 = 36'hzzzzzzzzz;
  assign GPIO_1 = 36'hzzzzzzzzz;

  // turn off hex leds
  assign HEX0 = 7'b1111111;
  assign HEX1 = 7'b1111111;
  assign HEX2 = 7'b1111111;
  assign HEX3 = 7'b1111111;
  assign HEX4 = 7'b1111111;
  assign HEX5 = 7'b1111111;

endmodule
